  - alias: Home detection
    trigger:
      platform: state
      entity_id: device_tracker.iphone_asagan
      to: 'home'
    action:
      service: notify.ios_iphone_arcanus
      data:
        message: "Witaj"
 
  - alias: Turn on Listwa Morning
    trigger:
      platform: time
      at: '7:30:00'
    action:
      service: mqtt.publish
      data:
        topic: /sonoff/listwa/switch/cmd
        payload: "on"
    
  - alias: Turn off Listwa Morning
    trigger:
      platform: time
      at: '11:00:00'
    condition:
    - condition: time
      weekday:
        - mon
        - tue
        - wed
        - thu
        - fri
    action:
      service: mqtt.publish
      data:
        topic: /sonoff/listwa/switch/cmd
        payload: "off"

  - alias: Turn on Listwa Afternoon
    trigger:
      platform: time
      at: '17:30:00'
    condition:
    - condition: time
      weekday:
        - mon
        - tue
        - wed
        - thu
        - fri
    action:
      service: mqtt.publish
      data:
        topic: /sonoff/listwa/switch/cmd
        payload: "on"
        
  - alias: Turn off Listwa Afternoon
    trigger:
      platform: time
      at: '01:00:00'
    action:
      service: mqtt.publish
      data:
        topic: /sonoff/listwa/switch/cmd
        payload: "off"
      
  - alias: Morning radio
    trigger:
      platform: time
      at: '7:45:00'
    condition:
    - condition: time
      weekday:
        - mon
        - tue
        - wed
        - thu
        - fri
    action:
      - service: media_player.play_media
        entity_id: media_player.mibox3
        data:
          media_content_id: https://zt02.cdn.eurozet.pl/zet-tun.mp3
          media_content_type: audio/mp4
      - service: media_player.volume_set
        entity_id: media_player.mibox3
        data_template:
          volume_level: '{{ 0.2 }}'