###########################################
# Media Switches
###########################################
- platform: mqtt
  name: "Power Strip"
  state_topic: "/sonoff/listwa/switch/state"
  command_topic: "/sonoff/listwa/switch/cmd"
#  availability_topic: "/sonoff/listwa/state"
  payload_on: "on"
  payload_off: "off"
  state_on: "on"
  state_off: "off"
#  payload_available: "connected"
#  payload_not_available: "disconnected"

- platform: mqtt
  name: "Corridor Light"
  state_topic: "/sonoff/aisle/switch/state"
  command_topic: "/sonoff/aisle/switch/cmd"
  payload_on: "on"
  payload_off: "off"
  state_on: "on"
  state_off: "off"

#- platform: command_line
#  switches:
#    arest_pin_four:
#      command_on: "/usr/bin/curl -X GET http://127.0.0.1:8123"
#      command_off: "/usr/bin/curl -X GET http://127.0.0.1:8123"
#      command_state: "/usr/bin/curl -X GET http://127.0.0.1:8123"
#      value_template: '{{ value == "1" }}'
#      friendly_name: Kitchen Lightswitch
        
- platform: template
  switches:
    radio:
      value_template: "{{is_state('media_player.mibox3', 'playing') }}"
      turn_on:
        service: media_player.play_media
        entity_id: media_player.mibox3
        data:
          media_content_id: https://zt02.cdn.eurozet.pl/zet-tun.mp3
          media_content_type: audio/mp4
      turn_off:
        service: media_player.turn_off
        entity_id: media_player.mibox3
        
- platform: broadlink
  host: !secret broadlink_ip
  mac: !secret broadlink_mac
  timeout: 15 
  switches:
    tv:
      friendly_name: "TV"
      command_on: 'JgBgAB8dHxs9HB8cHxsfOD4bHzgfHD0cHwALtB4dHh08HB8cHxweOTwdHjkeHD0cHwALtx4cHh08HR4cHh0eOTwdHjkeHD0cHgALtyAbHxw9HB8bHxwfOD0cHzgfGz4bHwANBQAAAAAAAAAA'
      command_off: 'JgBgAB8dHxs9HB8cHxsfOD4bHzgfHD0cHwALtB4dHh08HB8cHxweOTwdHjkeHD0cHwALtx4cHh08HR4cHh0eOTwdHjkeHD0cHgALtyAbHxw9HB8bHxwfOD0cHzgfGz4bHwANBQAAAAAAAAAA'
